### ISSUE TITLE
Bottom of tab bar doesn't reach all the way across the screen on big monitors

### ISSUE THREAD

**Issue by sambehrens** [dog-house-development/poodl#384]
STR:
1. Buy a really big monitor
2. Set it up
3. Open poodl
4. Go to a page with tabs like memer/:id or activities/:id
5. Observe the gaps on the ends of the line
5.5. Mourn the day that writing good css was standard practice

**Comment by karlmolina** [comment]
Or don't buy a big monitor and just zoom out.
